### ISSUE TITLE
Only writing the csv header

### ISSUE THREAD

**Issue by materia79** [sbvualo/pymsposd#1]
Hi there,

is pymsposd outdated due to a new OSD format? I am using the most recent wtfos/msp-osd.

Everything I get from my OSD files using pymsposd is this:

`latitude,longitude,altitude,speed,time_ms`

There is also no error showing up, the only output to the console is: `File "osdout.csv" written.`
Thanks!

**Comment by sbvualo** [comment]
Hi!

I don't see any recent changes to the .osd file format in wtfos/msp-osd.

pymsposd was tested only on DJI Goggles v1 + Betaflight.

Can you please provide your OSD file so that I can test and add support for your variant?

**Comment by materia79** [comment]
Ah then everything is probably different here. 

I am using DJI Goggles V2 (Not the new DJI Goggles 2, it is the V2 with the 4 antennas still). My FC is also running INAV 6.1.0 instead of Betaflight.

Just realized that I tried yesterday an OSD file without actual lat/long info on the screen but just retried it with one with coords and it was the same outcome.

Here an .osd file freshly recorded:
[DJIG0006.zip](https://github.com/sbvualo/pymsposd/files/13061575/DJIG0006.zip)

Thanks for you quick reply!

**Comment by sbvualo** [comment]
Fixed.

Please reopen the issue if still not working

**Comment by materia79** [comment]
Works perfect! Thanks for your effort!
